### ISSUE TITLE
Files not accessible with oxide launcher

### ISSUE THREAD

**Issue by plan5** [plan5/remarvin#6]
When launching xochitl in oxide, a chroot environment is used that won't include the decrypted gocryptfs mount.

It was introduced with https://github.com/Eeems-Org/oxide/pull/186 

Planned steps to fix this:

- [x] Understand the need for chroots when running apps from oxide
- [x] See if there is an easy fix that could be pushed to oxide to fix this (get the chroot to include bind mounts and/or gocryptfs mount)
- [ ] Otherwise: Explore other possibilities to fix this.

**Comment by plan5** [comment]
It might be enough to add two directories to the xochitl application config file in oxide [like it was done here](https://github.com/Eeems-Org/oxide/commit/94c16508075f0671aa33ae7bd93cd36587800fc7#diff-f0f3af61c9b5620dbbb6f7a24107215bec041c00d4626a4662a3be722dcdabd9)

These would be
> /home/root/.local/share
> /home/root/.local/share/remarkable

**Comment by Eeems** [comment]
> Understand the need for chroots when running apps from oxide

The reason is to catch when xochitl tries to power off or suspend the device since it doesn't use `systemctl`, it uses `/sys/power/state` directly instead: https://github.com/Eeems-Org/oxide/blob/master/applications/system-service/application.h#L709-L710

Also, is this still broken now that those mountpoints have been added?

**Comment by Eeems** [comment]
@plan5 poke?

**Comment by plan5** [comment]
> @plan5 poke?

Thanks for the reminder, tried to reach out to you on Matrix but it seems the bridge doesn't properly establish DM rooms? Anyway, I'm back at it.

**Comment by plan5** [comment]
> > Understand the need for chroots when running apps from oxide
> 
> The reason is to catch when xochitl tries to power off or suspend the device since it doesn't use `systemctl`, it uses `/sys/power/state` directly instead: https://github.com/Eeems-Org/oxide/blob/master/applications/system-service/application.h#L709-L710
> 
> Also, is this still broken now that those mountpoints have been added?

It works, thanks! I'm now looking into several other loosely connected issues but this is a big leap.
